name: Deploy to EC2

on:
   push:
      branches:
         - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REGISTRY=${{ secrets.REGISTRY }}
            REPO_NAME=myapp
            IMAGE_TAG=latest

            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin $REGISTRY
            docker pull $REGISTRY/$REPO_NAME:$IMAGE_TAG

            docker stop myapp || true
            docker rm myapp || true

            docker run -d --name myapp -p 80:80 $REGISTRY/$REPO_NAME:$IMAGE_TAG
